[package]
name = "net_mgr_handler"
version = "0.1.0"
authors = ["Nick Osterhold <nick.osterhold@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.8.3"